# Generated by Django 3.0.6 on 2020-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('manual', models.CharField(max_length=64)),
                ('tips', models.CharField(max_length=200)),
                ('voltage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=64)),
                ('start_date', models.IntegerField()),
                ('job_length', models.IntegerField()),
                ('job_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('location_details', models.CharField(max_length=1000)),
                ('ppe_requirements', models.CharField(max_length=1000)),
                ('site_considerations', models.CharField(max_length=2000)),
                ('quoted_price', models.IntegerField()),
                ('costs', models.IntegerField()),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipment', to='tracker.Equipment')),
                ('test_equipment', models.ManyToManyField(blank=True, related_name='test_equipment', to='tracker.TestEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('burn_rate', models.IntegerField()),
                ('jobs', models.ManyToManyField(blank=True, related_name='engineers', to='tracker.Job')),
            ],
        ),
    ]
