# Generated by Django 3.0.6 on 2020-07-06 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_auto_20200706_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=64)),
                ('equipment_questions', models.TextField(blank=True, null=True)),
                ('cloud_link', models.TextField(blank=True, null=True)),
                ('template_notes', models.TextField(blank=True, null=True)),
                ('test_sheet', models.FileField(blank=True, null=True, upload_to='')),
                ('equipment_help', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fsr', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_coordinator', models.BooleanField(default=False)),
                ('is_salesman', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('home_base', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('burn_rate', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='make',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tips',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='test_equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='scope',
            field=models.TextField(default='refer to overall job scope(default)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='site_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='test_sheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_lead',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='material',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='onedrive',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='site_contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='site_contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tools',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testequipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manual',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='tracker.Equipment'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='ppe_requirements',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='quoted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='site_considerations',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.AddField(
            model_name='template',
            name='recommended_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='recommended_test_equipment_template', to='tracker.TestEquipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='tracker.Template'),
        ),
        migrations.AddField(
            model_name='job',
            name='user_properties',
            field=models.ManyToManyField(blank=True, related_name='user_properties', to='tracker.UserProperties'),
        ),
    ]
