# Generated by Django 3.0.6 on 2020-07-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200706_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='equipment_help',
        ),
    ]
