# Generated by Django 3.0.6 on 2020-07-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_template_equipment_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='equipment_help',
            field=models.TextField(blank=True, null=True),
        ),
    ]
