# Generated by Django 3.0.6 on 2020-07-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200707_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_length',
        ),
    ]
