# Generated by Django 3.0.6 on 2020-08-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_job_job_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='scope',
            field=models.TextField(default='refer to overall job scope (default)'),
        ),
    ]
