# Generated by Django 3.0.6 on 2020-08-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20200813_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
