# Generated by Django 3.0.6 on 2020-08-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20200813_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='onedrive',
            new_name='online_job_folder',
        ),
    ]
