# Generated by Django 3.0.6 on 2020-08-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_job_nav_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='diesel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gasoline',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
