# Generated by Django 3.0.6 on 2020-08-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20200816_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='diesel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='gasoline',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
