# Generated by Django 3.0.6 on 2020-08-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20200816_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='Type',
        ),
    ]
