# Generated by Django 3.0.6 on 2020-08-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_auto_20200822_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='tracker.Type'),
        ),
    ]
