# Generated by Django 3.0.6 on 2020-08-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto_20200822_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='classification',
            new_name='name',
        ),
    ]
