# Generated by Django 3.0.6 on 2020-08-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_remove_type_equipment_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='template_notes',
            new_name='type_notes',
        ),
    ]
