# Generated by Django 3.0.6 on 2020-08-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_auto_20200822_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('customer_support', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
