# Generated by Django 3.0.6 on 2020-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20200825_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='equipment_type_supported',
        ),
        migrations.AddField(
            model_name='userproperties',
            name='equipment_models_supported',
            field=models.ManyToManyField(blank=True, related_name='equipment_models_supported', to='tracker.Model'),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='equipment_types_supported',
            field=models.ManyToManyField(blank=True, related_name='equipment_types_supported', to='tracker.Type'),
        ),
    ]
