# Generated by Django 3.0.6 on 2020-08-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20200825_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.AddField(
            model_name='model',
            name='model_customer_support',
            field=models.TextField(blank=True, null=True),
        ),
    ]
