# Generated by Django 3.0.6 on 2020-08-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_auto_20200825_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_model', to='tracker.Model'),
        ),
        migrations.AddField(
            model_name='model',
            name='model_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_manufacturer', to='tracker.Manufacturer'),
        ),
        migrations.AddField(
            model_name='model',
            name='model_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_type', to='tracker.Type'),
        ),
    ]
