# Generated by Django 3.0.6 on 2020-09-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_auto_20200918_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='optional_type_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='optional_type_test_equipment', to='tracker.TestEquipment'),
        ),
        migrations.AlterField(
            model_name='type',
            name='mandatory_type_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='mandatory_type_test_equipment', to='tracker.TestEquipment'),
        ),
    ]
