# Generated by Django 3.0.6 on 2020-09-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_auto_20200918_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='model_test_equipment',
            new_name='mandatory_model_test_equipment',
        ),
    ]
