# Generated by Django 3.0.6 on 2020-09-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_auto_20200920_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='optional_model_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='optional_model_test_equipment', to='tracker.TestEquipment'),
        ),
        migrations.AlterField(
            model_name='model',
            name='mandatory_model_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='mandatory_model_test_equipment', to='tracker.TestEquipment'),
        ),
    ]
