# Generated by Django 3.0.6 on 2020-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0046_auto_20200920_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='site_id',
            field=models.TextField(default='default_siteID', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
