# Generated by Django 3.0.6 on 2020-09-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_auto_20200925_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_type_specified',
            new_name='equipment_type',
        ),
    ]
