# Generated by Django 3.0.6 on 2020-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_auto_20200925_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mandatory_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='mandatory_test_equipment', to='tracker.TestEquipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='optional_test_equipment',
            field=models.ManyToManyField(blank=True, related_name='optional_test_equipment', to='tracker.TestEquipment'),
        ),
    ]
