# Generated by Django 3.0.6 on 2020-10-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0050_model_model_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_lead',
            new_name='project_manager',
        ),
        migrations.AddField(
            model_name='job',
            name='customer_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='site_id',
            field=models.TextField(max_length=1000),
        ),
    ]
