# Generated by Django 3.0.6 on 2020-10-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0053_auto_20201006_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='dangerous_chemical_exposure',
            new_name='chemical_hazards',
        ),
    ]
