# Generated by Django 3.0.6 on 2020-10-09 03:13

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0055_auto_20201008_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='test_sheet',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_type_te_path),
        ),
    ]
