# Generated by Django 3.0.6 on 2020-10-10 00:39

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0056_auto_20201008_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_test_sheet',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_model_te_path),
        ),
    ]
