# Generated by Django 3.0.6 on 2020-10-10 00:53

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0057_auto_20201009_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_test_guide',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_model_tg_path),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_test_guide',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_type_tg_path),
        ),
    ]
