# Generated by Django 3.0.6 on 2020-10-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0058_auto_20201009_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quoted_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
