# Generated by Django 3.0.6 on 2020-10-11 06:40

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0061_auto_20201011_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='test_sheet_template',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_eq_testsheet_template_path),
        ),
    ]
