# Generated by Django 3.0.6 on 2020-10-11 17:57

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0062_equipment_test_sheet_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_file', models.FileField(blank=True, null=True, upload_to=tracker.models.job_folder_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='online_job_folder',
        ),
        migrations.AddField(
            model_name='job',
            name='job_folder',
            field=models.ManyToManyField(blank=True, related_name='job_folder', to='tracker.JobFolder'),
        ),
    ]
