# Generated by Django 3.0.6 on 2020-10-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0063_auto_20201011_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_folder',
        ),
        migrations.AddField(
            model_name='jobfolder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='tracker.Job'),
        ),
    ]
