# Generated by Django 3.0.6 on 2020-10-18 18:14

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0067_modelfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='test_results',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_test_results_path),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='test_sheet_template',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_eq_testsheet_template_path),
        ),
        migrations.AlterField(
            model_name='equipmentfolder',
            name='equipment_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.equipment_folder_path),
        ),
        migrations.AlterField(
            model_name='jobfolder',
            name='job_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.job_folder_path),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_manual',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_test_guide',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_model_tg_path),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_test_sheet',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_model_te_path),
        ),
        migrations.AlterField(
            model_name='modelfolder',
            name='model_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.model_folder_path),
        ),
        migrations.AlterField(
            model_name='type',
            name='test_sheet',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_type_te_path),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_test_guide',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_type_tg_path),
        ),
    ]
