# Generated by Django 3.0.6 on 2020-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0068_auto_20201018_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
