# Generated by Django 3.0.6 on 2020-10-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0072_equipmentnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentnotes',
            old_name='job',
            new_name='equipment',
        ),
    ]
