# Generated by Django 3.0.6 on 2020-11-07 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0073_auto_20201031_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfolder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
