# Generated by Django 3.0.6 on 2020-11-14 21:45

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0075_auto_20201106_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='ansi_standards',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_type_ansi_path),
        ),
        migrations.AddField(
            model_name='type',
            name='neta_standards',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_type_neta_path),
        ),
    ]
