# Generated by Django 3.0.6 on 2020-11-20 23:49

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0076_auto_20201114_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTestGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_test_guide', models.FileField(blank=True, max_length=1000, null=True, upload_to=tracker.models.type_testguide_path)),
                ('title', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eq_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_test', to='tracker.Type')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.type_folder_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eq_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_type', to='tracker.Type')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTestGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_test_guide', models.FileField(blank=True, max_length=1000, null=True, upload_to=tracker.models.model_testguide_path)),
                ('title', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_test', to='tracker.Model')),
            ],
        ),
    ]
