# Generated by Django 3.0.6 on 2020-11-21 14:59

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0077_modeltestguide_typefolder_typetestguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='nameplate',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=tracker.models.upload_nameplate_path),
        ),
    ]
