# Generated by Django 3.0.6 on 2020-11-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_equipment_nameplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('owner', models.CharField(blank=True, max_length=128, null=True)),
                ('facility_manager', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('nav_link', models.URLField(blank=True, max_length=300, null=True)),
                ('site_navigation', models.TextField(blank=True, null=True)),
                ('site_contact', models.TextField(blank=True, null=True)),
                ('site_contact_info', models.TextField(blank=True, null=True)),
                ('other_contacts', models.TextField(blank=True, null=True)),
                ('food_accomodations', models.TextField(blank=True, null=True)),
                ('lodging_recommendations', models.TextField(blank=True, null=True)),
                ('is_safety_training', models.BooleanField(default=False)),
                ('safety_training_item_requirements', models.TextField(blank=True, null=True)),
                ('safety_training_time', models.TextField(blank=True, null=True)),
                ('safety_training_location', models.TextField(blank=True, null=True)),
                ('safety_training_procedure', models.TextField(blank=True, null=True)),
                ('safety_rules', models.TextField(blank=True, null=True)),
                ('is_hardhat', models.BooleanField(default=False)),
                ('is_safety_glasses', models.BooleanField(default=False)),
                ('is_safety_shoes', models.BooleanField(default=False)),
                ('is_safety_vest', models.BooleanField(default=False)),
                ('is_safety_gloves', models.BooleanField(default=False)),
                ('is_fr_clothes', models.BooleanField(default=False)),
                ('is_h2s_monitor', models.BooleanField(default=False)),
                ('additional_ppe_requirements', models.TextField(blank=True, null=True)),
                ('documents_required_for_access', models.TextField(blank=True, null=True)),
                ('background_checks', models.BooleanField(default=False)),
                ('background_check_procedure', models.TextField(blank=True, null=True)),
                ('access_requirements', models.TextField(blank=True, null=True)),
                ('entry_procedure', models.TextField(blank=True, null=True)),
                ('restricted_items', models.TextField(blank=True, null=True)),
                ('driving_vehicles', models.TextField(blank=True, null=True)),
                ('parking_considerations', models.TextField(blank=True, null=True)),
                ('other_site_rules', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
