# Generated by Django 3.0.6 on 2020-11-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0080_jobsitefolder_jobsitenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_site', to='tracker.JobSite'),
        ),
    ]
