# Generated by Django 3.0.6 on 2020-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0082_auto_20201123_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='quote_default',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
