# Generated by Django 3.0.6 on 2020-11-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0083_auto_20201123_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='quote_default',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
