# Generated by Django 3.0.6 on 2020-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0085_auto_20201125_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsitefolder',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modelfolder',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typefolder',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
