# Generated by Django 3.0.6 on 2021-03-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0088_auto_20210302_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='tracker.Company'),
        ),
    ]
