# Generated by Django 3.0.6 on 2021-03-07 21:36

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0089_auto_20210304_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_safety_analysis',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_company_jsa_path),
        ),
        migrations.AddField(
            model_name='company',
            name='time_sheet',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.upload_company_time_sheet),
        ),
    ]
