# Generated by Django 3.0.6 on 2021-05-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0095_auto_20210513_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobsite_company', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_company', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='model',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eq_type_company', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='type',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
