# Generated by Django 3.0.6 on 2021-06-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0098_testsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='pi_testamps_gfd',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
