# Generated by Django 3.0.6 on 2021-06-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0099_testsheet_pi_testamps_gfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='eq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_eq', to='tracker.Equipment'),
        ),
    ]
