# Generated by Django 3.0.6 on 2021-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0100_testsheet_eq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='date_manufactured',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsheet',
            name='date_tested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
