# Generated by Django 3.0.6 on 2021-06-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0101_auto_20210624_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='trip_unit_manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testsheet',
            name='trip_unit_serial_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
