# Generated by Django 3.0.6 on 2021-07-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0102_auto_20210624_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_ratio',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_ratio',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_ratio',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_ratio',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_ratio',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_ratio',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_h12_x02',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_h23_x03',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_h31_x01',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_ratio',
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_amp_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_conductor_material',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_ending_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_insulation_thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_insulation_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_starting_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_test_voltage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_voltage_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_withstand_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cubicle_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fifteen_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='finger_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='five_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fourtyfive_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_a',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_b',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_c',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_secondary_a',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_secondary_b',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_secondary_c',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_cable_shielded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_cable_vlf_withstand_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='mechanical_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='one_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='operating_cable_voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='racking_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='shutter_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='sixty_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ten_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='test_frequency',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='thirty_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twenty_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test_current_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test_current_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test_current_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test_resistance_pha',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test_resistance_phb',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='twentyfive_min_cable_test_resistance_phc',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='vacuum_bottle_condition',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
