# Generated by Django 3.0.6 on 2021-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0104_auto_20210708_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_test_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
