# Generated by Django 3.0.6 on 2021-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0106_auto_20210713_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_ttr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_xfmr_insulation_resistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='hipot_test_voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_cubicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_ground_connections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_insulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_open_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='inspect_racking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_resistance_hi_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_resistance_hi_g_test_voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_resistance_hi_lo',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_resistance_hi_lo_test_voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_resistance_lo_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='insulation_resistance_lo_g_test_voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_dc_control_voltage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_dc_trip_voltage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='protection_device',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ttr_lower_tolerance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='ttr_upper_tolerance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='is_ttr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='type',
            name='is_xfmr_insulation_resistance',
            field=models.BooleanField(default=False),
        ),
    ]
