# Generated by Django 3.0.6 on 2021-07-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0108_auto_20210726_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_five_h31_x01_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_four_h31_x01_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_one_h31_x01_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_seven_h31_x01_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_six_h31_x01_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_three_h31_x01_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_h12_x02_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_h23_x03_ttr_error',
        ),
        migrations.RemoveField(
            model_name='testsheet',
            name='tap_two_h31_x01_ttr_error',
        ),
    ]
