# Generated by Django 3.0.6 on 2021-08-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0110_auto_20210803_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='job_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_jobsite', to='tracker.JobSite'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parent_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_equipments', to='tracker.Equipment'),
        ),
    ]
