# Generated by Django 3.0.6 on 2021-08-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0111_auto_20210812_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.JobNotes'),
        ),
    ]
