# Generated by Django 3.0.6 on 2021-09-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0112_jobnotes_parent_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobnotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_job_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
