# Generated by Django 3.0.6 on 2021-09-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0113_auto_20210908_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentnotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentnotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.EquipmentNotes'),
        ),
        migrations.AddField(
            model_name='equipmentnotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_equipment_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.ModelNotes'),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_model_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='parent_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tracker.TypeNotes'),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_type_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
