# Generated by Django 3.0.6 on 2021-09-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0114_auto_20210909_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_mold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casting', to='tracker.Equipment'),
        ),
    ]
