# Generated by Django 3.0.6 on 2021-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0115_equipment_equipment_mold'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='test_equipment',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='tracker.TestEquipment'),
        ),
    ]
