# Generated by Django 3.0.6 on 2021-09-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0116_job_test_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True),
        ),
    ]
