# Generated by Django 3.0.6 on 2021-09-28 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0117_auto_20210927_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeteststandards',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_test_standards', to=settings.AUTH_USER_MODEL),
        ),
    ]
