# Generated by Django 3.0.6 on 2021-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0119_auto_20210929_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_testing',
            field=models.BooleanField(default=True),
        ),
    ]
