# Generated by Django 3.0.6 on 2021-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0121_auto_20211001_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True),
        ),
    ]
