# Generated by Django 3.0.6 on 2021-10-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0124_auto_20211013_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='equipment_voltage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_dc_equipment_voltage',
            field=models.BooleanField(default=False),
        ),
    ]
