# Generated by Django 3.0.6 on 2021-10-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0126_workingnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingnote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workingnote',
            name='updated_at',
        ),
    ]
