# Generated by Django 3.0.6 on 2021-11-09 18:04

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0127_auto_20211025_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('oil_change_date', models.DateField(blank=True, max_length=80, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('completed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('motor', models.CharField(blank=True, max_length=256, null=True)),
                ('oil_type', models.CharField(blank=True, max_length=256, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=256, null=True)),
                ('oil_filter', models.TextField(blank=True, null=True)),
                ('air_filter', models.TextField(blank=True, null=True)),
                ('oil_capacity', models.IntegerField(blank=True, null=True)),
                ('hours_last', models.IntegerField(blank=True, null=True)),
                ('hours_next', models.IntegerField(blank=True, null=True)),
                ('overhaul_frequency', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, max_length=80, null=True)),
                ('man_date', models.DateField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_well', to='tracker.Well')),
            ],
        ),
        migrations.CreateModel(
            name='MaintNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_maint', to='tracker.MaintEvent')),
            ],
        ),
        migrations.CreateModel(
            name='MaintFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maint_file', models.FileField(blank=True, max_length=500, null=True, upload_to=tracker.models.maint_file_path)),
                ('file_name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maint_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maint_event_file', to='tracker.MaintEvent')),
            ],
        ),
    ]
