# Generated by Django 3.0.6 on 2021-11-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0130_auto_20211109_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintevent',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maint_well', to='tracker.Well'),
        ),
    ]
