# Generated by Django 3.0.6 on 2021-12-02 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0133_auto_20211201_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfolder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_model_file', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='modelnotes',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_model_note', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='modeltestguide',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_model_video', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='typefolder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_type_file', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='typenotes',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_type_note', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='typetestguide',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_type_video', to='tracker.Company'),
        ),
        migrations.AddField(
            model_name='typeteststandards',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_ts', to='tracker.Company'),
        ),
    ]
