# Generated by Django 3.0.6 on 2021-12-08 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0134_auto_20211201_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsitenotes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
