# Generated by Django 3.0.6 on 2022-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0136_equipmentfolder_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='cable_ending_termination_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_insulation_material',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_starting_termination_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='is_133_cable_insulation',
            field=models.BooleanField(default=False),
        ),
    ]
