# Generated by Django 3.0.6 on 2022-03-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0140_auto_20220308_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabletestdata',
            name='test_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cable_test_data', to='tracker.TestSheet'),
        ),
    ]
