# Generated by Django 3.0.6 on 2022-03-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0141_auto_20220308_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='cable_hipot_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
