# Generated by Django 3.0.6 on 2022-03-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0142_testsheet_cable_hipot_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='cable_ending_point',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testsheet',
            name='cable_starting_point',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
