# Generated by Django 3.0.6 on 2022-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0143_auto_20220311_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='cable_insulation_thickness_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
