# Generated by Django 3.0.6 on 2022-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0144_testsheet_cable_insulation_thickness_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='cable_length_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
