# Generated by Django 3.0.6 on 2022-03-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0146_testsheet_cable_size_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='cable_conductor_material_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
