# Generated by Django 3.0.6 on 2022-03-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0147_testsheet_cable_conductor_material_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsheet',
            name='cable_conductor_material_units',
        ),
    ]
