# Generated by Django 3.0.6 on 2022-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0148_remove_testsheet_cable_conductor_material_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='cable_size',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
