# Generated by Django 3.0.6 on 2022-03-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0150_auto_20220313_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsheet',
            name='is_133_cable_insulation',
        ),
        migrations.AddField(
            model_name='testsheet',
            name='cable_insulation_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
