# Generated by Django 3.0.6 on 2022-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0153_auto_20220404_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='page_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
