# Generated by Django 3.0.6 on 2022-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0155_auto_20220407_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsheet',
            name='page_quantity',
        ),
        migrations.AddField(
            model_name='type',
            name='ts_page_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
