# Generated by Django 3.0.6 on 2022-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0156_auto_20220411_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_lv_ic_or_mc_breaker',
            field=models.BooleanField(default=False),
        ),
    ]
