# Generated by Django 3.0.6 on 2022-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0157_type_is_lv_ic_or_mc_breaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_mv_or_hv_breaker',
            field=models.BooleanField(default=False),
        ),
    ]
