# Generated by Django 3.0.6 on 2022-04-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0158_type_is_mv_or_hv_breaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='operating_voltage',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
    ]
