# Generated by Django 3.0.6 on 2022-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0160_testsheet_is_dc_operating_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='fuse_sizes_types_drawings_ect',
            field=models.BooleanField(default=False),
        ),
    ]
