# Generated by Django 3.0.6 on 2022-04-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0161_testsheet_fuse_sizes_types_drawings_ect'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='correct_aux_in_out',
            field=models.BooleanField(default=False),
        ),
    ]
