# Generated by Django 3.0.6 on 2022-04-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0162_testsheet_correct_aux_in_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='measurements_indications_consistant_standards',
            field=models.BooleanField(default=False),
        ),
    ]
