# Generated by Django 3.0.6 on 2022-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0163_testsheet_measurements_indications_consistant_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='clearances_primary_secondary_wiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='connections_with_system_requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='grounding_connections_contact',
            field=models.BooleanField(default=False),
        ),
    ]
