# Generated by Django 3.0.6 on 2022-04-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0164_auto_20220417_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_a_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_b_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_c_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_secondary_a_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_secondary_b_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='testsheet',
            name='fuse_resistance_secondary_c_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
