# Generated by Django 3.0.6 on 2022-04-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0165_auto_20220419_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabletestdata',
            name='phase_a_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cabletestdata',
            name='phase_b_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cabletestdata',
            name='phase_c_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='BusContactTestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result_key', models.IntegerField(blank=True, null=True)),
                ('starting_section', models.TextField(blank=True, null=True)),
                ('ending_section', models.TextField(blank=True, null=True)),
                ('phase_a', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('phase_b', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('phase_c', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('test_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_test_data', to='tracker.TestSheet')),
            ],
        ),
    ]
