# Generated by Django 3.0.6 on 2022-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0166_auto_20220422_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscontacttestdata',
            name='phase_a_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='buscontacttestdata',
            name='phase_b_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='buscontacttestdata',
            name='phase_c_units',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
