# Generated by Django 3.0.6 on 2022-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0171_testsheet_is_dc_system_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='tap_qty',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
