# Generated by Django 3.0.6 on 2022-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0172_auto_20220426_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='equipment_notifications',
            field=models.ManyToManyField(blank=True, related_name='equipment_notifications_user', to='tracker.Equipment'),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='is_all_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='job_notifications',
            field=models.ManyToManyField(blank=True, related_name='job_notifications_user', to='tracker.Job'),
        ),
    ]
