# Generated by Django 3.2 on 2022-08-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0174_auto_20220830_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='change_key',
            field=models.IntegerField(default=0),
        ),
    ]
